/* Generated By:JavaCC: Do not edit this line. GraceCompilerConstants.java */
package main;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GraceCompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int _DEF = 5;
  /** RegularExpression Id. */
  int _VAR = 6;
  /** RegularExpression Id. */
  int _TYPE = 7;
  /** RegularExpression Id. */
  int _LPAR = 8;
  /** RegularExpression Id. */
  int _RPAR = 9;
  /** RegularExpression Id. */
  int _LBRACE = 10;
  /** RegularExpression Id. */
  int _RBRACE = 11;
  /** RegularExpression Id. */
  int _LBRACK = 12;
  /** RegularExpression Id. */
  int _RBRACK = 13;
  /** RegularExpression Id. */
  int _COMMA = 14;
  /** RegularExpression Id. */
  int _SEMICOLON = 15;
  /** RegularExpression Id. */
  int _SUM = 16;
  /** RegularExpression Id. */
  int _SUB = 17;
  /** RegularExpression Id. */
  int _MULT = 18;
  /** RegularExpression Id. */
  int _DIV = 19;
  /** RegularExpression Id. */
  int _MOD = 20;
  /** RegularExpression Id. */
  int _EQUAL = 21;
  /** RegularExpression Id. */
  int _NEQUAL = 22;
  /** RegularExpression Id. */
  int _GTHAN = 23;
  /** RegularExpression Id. */
  int _LTHAN = 24;
  /** RegularExpression Id. */
  int _GEQUAL = 25;
  /** RegularExpression Id. */
  int _LEQUAL = 26;
  /** RegularExpression Id. */
  int _LOG_OR = 27;
  /** RegularExpression Id. */
  int _LOG_AND = 28;
  /** RegularExpression Id. */
  int _LOG_NOT = 29;
  /** RegularExpression Id. */
  int _ASSIGN = 30;
  /** RegularExpression Id. */
  int _SUM_ASSIGN = 31;
  /** RegularExpression Id. */
  int _SUB_ASSIGN = 32;
  /** RegularExpression Id. */
  int _MULT_ASSIGN = 33;
  /** RegularExpression Id. */
  int _DIV_ASSIGN = 34;
  /** RegularExpression Id. */
  int _MOD_ASSIGN = 35;
  /** RegularExpression Id. */
  int _COND = 36;
  /** RegularExpression Id. */
  int _COLON = 37;
  /** RegularExpression Id. */
  int _IF = 38;
  /** RegularExpression Id. */
  int _ELSE = 39;
  /** RegularExpression Id. */
  int _FOR = 40;
  /** RegularExpression Id. */
  int _WHILE = 41;
  /** RegularExpression Id. */
  int _READ = 42;
  /** RegularExpression Id. */
  int _WRITE = 43;
  /** RegularExpression Id. */
  int _SKIP = 44;
  /** RegularExpression Id. */
  int _STOP = 45;
  /** RegularExpression Id. */
  int _RETURN = 46;
  /** RegularExpression Id. */
  int _ID = 47;
  /** RegularExpression Id. */
  int _BOOL = 48;
  /** RegularExpression Id. */
  int _INT = 49;
  /** RegularExpression Id. */
  int _STR = 50;
  /** RegularExpression Id. */
  int _CHAR = 51;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<token of kind 4>",
    "\"def\"",
    "\"var\"",
    "<_TYPE>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"||\"",
    "\"&&\"",
    "\"!\"",
    "\"=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"?\"",
    "\":\"",
    "\"if\"",
    "\"else\"",
    "\"for\"",
    "\"while\"",
    "\"read\"",
    "\"write\"",
    "\"skip\"",
    "\"stop\"",
    "\"return\"",
    "<_ID>",
    "<_BOOL>",
    "<_INT>",
    "<_STR>",
    "<_CHAR>",
  };

}
